version: '3.9'

services:
  web: 
    container_name: intrack-server
    build: 
      context: .
      target: production
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    command: npm run start:prod
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - redis
    
  redis:
    container_name: redis
    image: redis:7
    volumes:
      - redis:/data
    ports:
      - 6379:6379  
    networks:
      - webnet
  
networks:
  webnet:
    driver: bridge
    
volumes:
  redis:
    driver: local
  pgdata: